apiVersion: v1
kind: Service
metadata:
  name: tb-broker-loadbalancer-external
  namespace: thingsboard-mqtt-broker
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: tb-broker
  ports:
    - port: 80
      targetPort: 8083
      name: http
    - port: 1883
      targetPort: 1883
      name: mqtt